// Minimal broker proto for karpenter-provider-rafay. Wire format matches edge-common rep.edge.v1
// for EdgeCommand on EdgeCommandService.Execute (same bidi stream as edge-client).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v6.33.4
// source: pkg/brokerproto/broker.proto

package brokerproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// --- Enums (field numbers must match edge-common where applicable) ---
type EdgeCommandType int32

const (
	EdgeCommandType_EdgeCommandTypeIgnore EdgeCommandType = 0
	EdgeCommandType_KarpenterAddNode      EdgeCommandType = 17
	EdgeCommandType_KarpenterRemoveNode   EdgeCommandType = 18
)

// Enum value maps for EdgeCommandType.
var (
	EdgeCommandType_name = map[int32]string{
		0:  "EdgeCommandTypeIgnore",
		17: "KarpenterAddNode",
		18: "KarpenterRemoveNode",
	}
	EdgeCommandType_value = map[string]int32{
		"EdgeCommandTypeIgnore": 0,
		"KarpenterAddNode":      17,
		"KarpenterRemoveNode":   18,
	}
)

func (x EdgeCommandType) Enum() *EdgeCommandType {
	p := new(EdgeCommandType)
	*p = x
	return p
}

func (x EdgeCommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EdgeCommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_brokerproto_broker_proto_enumTypes[0].Descriptor()
}

func (EdgeCommandType) Type() protoreflect.EnumType {
	return &file_pkg_brokerproto_broker_proto_enumTypes[0]
}

func (x EdgeCommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EdgeCommandType.Descriptor instead.
func (EdgeCommandType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_brokerproto_broker_proto_rawDescGZIP(), []int{0}
}

type EdgeMessageType int32

const (
	EdgeMessageType_EdgeMessageTypeIgnore       EdgeMessageType = 0
	EdgeMessageType_KarpenterAddNodeRequest     EdgeMessageType = 33
	EdgeMessageType_KarpenterAddNodeResponse    EdgeMessageType = 34
	EdgeMessageType_KarpenterRemoveNodeRequest  EdgeMessageType = 35
	EdgeMessageType_KarpenterRemoveNodeResponse EdgeMessageType = 36
)

// Enum value maps for EdgeMessageType.
var (
	EdgeMessageType_name = map[int32]string{
		0:  "EdgeMessageTypeIgnore",
		33: "KarpenterAddNodeRequest",
		34: "KarpenterAddNodeResponse",
		35: "KarpenterRemoveNodeRequest",
		36: "KarpenterRemoveNodeResponse",
	}
	EdgeMessageType_value = map[string]int32{
		"EdgeMessageTypeIgnore":       0,
		"KarpenterAddNodeRequest":     33,
		"KarpenterAddNodeResponse":    34,
		"KarpenterRemoveNodeRequest":  35,
		"KarpenterRemoveNodeResponse": 36,
	}
)

func (x EdgeMessageType) Enum() *EdgeMessageType {
	p := new(EdgeMessageType)
	*p = x
	return p
}

func (x EdgeMessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EdgeMessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_brokerproto_broker_proto_enumTypes[1].Descriptor()
}

func (EdgeMessageType) Type() protoreflect.EnumType {
	return &file_pkg_brokerproto_broker_proto_enumTypes[1]
}

func (x EdgeMessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EdgeMessageType.Descriptor instead.
func (EdgeMessageType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_brokerproto_broker_proto_rawDescGZIP(), []int{1}
}

// Status matches rep.edge.v1.Status (edge-common).
type Status int32

const (
	Status_Accepted Status = 0
	Status_Success  Status = 1
	Status_Failed   Status = 2
	Status_Timeout  Status = 3
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "Accepted",
		1: "Success",
		2: "Failed",
		3: "Timeout",
	}
	Status_value = map[string]int32{
		"Accepted": 0,
		"Success":  1,
		"Failed":   2,
		"Timeout":  3,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_brokerproto_broker_proto_enumTypes[2].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_pkg_brokerproto_broker_proto_enumTypes[2]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_pkg_brokerproto_broker_proto_rawDescGZIP(), []int{2}
}

// --- Payloads: must match rep.edge.v1.KarpenterAddNodeCommand / KarpenterRemoveNodeCommand (edge-common edge.proto). ---
type KarpenterAddNodeCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EdgeId       string `protobuf:"bytes,1,opt,name=edge_id,json=edgeId,proto3" json:"edge_id,omitempty"`
	StreamId     string `protobuf:"bytes,2,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	ClusterId    string `protobuf:"bytes,3,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	ProjectId    string `protobuf:"bytes,4,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	InstanceType string `protobuf:"bytes,5,opt,name=instance_type,json=instanceType,proto3" json:"instance_type,omitempty"`
	NodePoolName string `protobuf:"bytes,6,opt,name=node_pool_name,json=nodePoolName,proto3" json:"node_pool_name,omitempty"`
}

func (x *KarpenterAddNodeCommand) Reset() {
	*x = KarpenterAddNodeCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_brokerproto_broker_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KarpenterAddNodeCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KarpenterAddNodeCommand) ProtoMessage() {}

func (x *KarpenterAddNodeCommand) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_brokerproto_broker_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KarpenterAddNodeCommand.ProtoReflect.Descriptor instead.
func (*KarpenterAddNodeCommand) Descriptor() ([]byte, []int) {
	return file_pkg_brokerproto_broker_proto_rawDescGZIP(), []int{0}
}

func (x *KarpenterAddNodeCommand) GetEdgeId() string {
	if x != nil {
		return x.EdgeId
	}
	return ""
}

func (x *KarpenterAddNodeCommand) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *KarpenterAddNodeCommand) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *KarpenterAddNodeCommand) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *KarpenterAddNodeCommand) GetInstanceType() string {
	if x != nil {
		return x.InstanceType
	}
	return ""
}

func (x *KarpenterAddNodeCommand) GetNodePoolName() string {
	if x != nil {
		return x.NodePoolName
	}
	return ""
}

type KarpenterRemoveNodeCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EdgeId     string `protobuf:"bytes,1,opt,name=edge_id,json=edgeId,proto3" json:"edge_id,omitempty"`
	StreamId   string `protobuf:"bytes,2,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	ProviderId string `protobuf:"bytes,3,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
}

func (x *KarpenterRemoveNodeCommand) Reset() {
	*x = KarpenterRemoveNodeCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_brokerproto_broker_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KarpenterRemoveNodeCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KarpenterRemoveNodeCommand) ProtoMessage() {}

func (x *KarpenterRemoveNodeCommand) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_brokerproto_broker_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KarpenterRemoveNodeCommand.ProtoReflect.Descriptor instead.
func (*KarpenterRemoveNodeCommand) Descriptor() ([]byte, []int) {
	return file_pkg_brokerproto_broker_proto_rawDescGZIP(), []int{1}
}

func (x *KarpenterRemoveNodeCommand) GetEdgeId() string {
	if x != nil {
		return x.EdgeId
	}
	return ""
}

func (x *KarpenterRemoveNodeCommand) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *KarpenterRemoveNodeCommand) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

// EdgeCommand is what edge-client receives on EdgeCommandService.Execute (stream).
// Fields 1–4 and 14 align with edge-common; 21–22 carry Karpenter ops (same wire as extended edge-common).
type EdgeCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommandType                EdgeCommandType             `protobuf:"varint,1,opt,name=command_type,json=commandType,proto3,enum=rep.edge.v1.EdgeCommandType" json:"command_type,omitempty"`
	MessageType                EdgeMessageType             `protobuf:"varint,2,opt,name=message_type,json=messageType,proto3,enum=rep.edge.v1.EdgeMessageType" json:"message_type,omitempty"`
	Data                       string                      `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Status                     Status                      `protobuf:"varint,4,opt,name=status,proto3,enum=rep.edge.v1.Status" json:"status,omitempty"`
	Rid                        string                      `protobuf:"bytes,14,opt,name=rid,proto3" json:"rid,omitempty"`
	KarpenterAddNodeCommand    *KarpenterAddNodeCommand    `protobuf:"bytes,21,opt,name=karpenter_add_node_command,json=karpenterAddNodeCommand,proto3" json:"karpenter_add_node_command,omitempty"`
	KarpenterRemoveNodeCommand *KarpenterRemoveNodeCommand `protobuf:"bytes,22,opt,name=karpenter_remove_node_command,json=karpenterRemoveNodeCommand,proto3" json:"karpenter_remove_node_command,omitempty"`
}

func (x *EdgeCommand) Reset() {
	*x = EdgeCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_brokerproto_broker_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EdgeCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EdgeCommand) ProtoMessage() {}

func (x *EdgeCommand) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_brokerproto_broker_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EdgeCommand.ProtoReflect.Descriptor instead.
func (*EdgeCommand) Descriptor() ([]byte, []int) {
	return file_pkg_brokerproto_broker_proto_rawDescGZIP(), []int{2}
}

func (x *EdgeCommand) GetCommandType() EdgeCommandType {
	if x != nil {
		return x.CommandType
	}
	return EdgeCommandType_EdgeCommandTypeIgnore
}

func (x *EdgeCommand) GetMessageType() EdgeMessageType {
	if x != nil {
		return x.MessageType
	}
	return EdgeMessageType_EdgeMessageTypeIgnore
}

func (x *EdgeCommand) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *EdgeCommand) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_Accepted
}

func (x *EdgeCommand) GetRid() string {
	if x != nil {
		return x.Rid
	}
	return ""
}

func (x *EdgeCommand) GetKarpenterAddNodeCommand() *KarpenterAddNodeCommand {
	if x != nil {
		return x.KarpenterAddNodeCommand
	}
	return nil
}

func (x *EdgeCommand) GetKarpenterRemoveNodeCommand() *KarpenterRemoveNodeCommand {
	if x != nil {
		return x.KarpenterRemoveNodeCommand
	}
	return nil
}

// Response bodies serialized into EdgeCommand.data for Karpenter*Response message types.
type AddNodeResponsePayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProviderIds []string `protobuf:"bytes,1,rep,name=provider_ids,json=providerIds,proto3" json:"provider_ids,omitempty"`
}

func (x *AddNodeResponsePayload) Reset() {
	*x = AddNodeResponsePayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_brokerproto_broker_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddNodeResponsePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddNodeResponsePayload) ProtoMessage() {}

func (x *AddNodeResponsePayload) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_brokerproto_broker_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddNodeResponsePayload.ProtoReflect.Descriptor instead.
func (*AddNodeResponsePayload) Descriptor() ([]byte, []int) {
	return file_pkg_brokerproto_broker_proto_rawDescGZIP(), []int{3}
}

func (x *AddNodeResponsePayload) GetProviderIds() []string {
	if x != nil {
		return x.ProviderIds
	}
	return nil
}

type RemoveNodeResponsePayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *RemoveNodeResponsePayload) Reset() {
	*x = RemoveNodeResponsePayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_brokerproto_broker_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveNodeResponsePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveNodeResponsePayload) ProtoMessage() {}

func (x *RemoveNodeResponsePayload) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_brokerproto_broker_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveNodeResponsePayload.ProtoReflect.Descriptor instead.
func (*RemoveNodeResponsePayload) Descriptor() ([]byte, []int) {
	return file_pkg_brokerproto_broker_proto_rawDescGZIP(), []int{4}
}

func (x *RemoveNodeResponsePayload) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_pkg_brokerproto_broker_proto protoreflect.FileDescriptor

var file_pkg_brokerproto_broker_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x70, 0x6b, 0x67, 0x2f, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b,
	0x72, 0x65, 0x70, 0x2e, 0x65, 0x64, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x22, 0xd8, 0x01, 0x0a, 0x17,
	0x4b, 0x61, 0x72, 0x70, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x41, 0x64, 0x64, 0x4e, 0x6f, 0x64, 0x65,
	0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x65, 0x64, 0x67, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x64, 0x67, 0x65, 0x49, 0x64,
	0x12, 0x1b, 0x0a, 0x09, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x49, 0x64, 0x12, 0x1d, 0x0a,
	0x0a, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a,
	0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x69,
	0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x24, 0x0a, 0x0e, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x70, 0x6f, 0x6f, 0x6c, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6e, 0x6f, 0x64, 0x65, 0x50, 0x6f,
	0x6f, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x73, 0x0a, 0x1a, 0x4b, 0x61, 0x72, 0x70, 0x65, 0x6e,
	0x74, 0x65, 0x72, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x43, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x65, 0x64, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x64, 0x67, 0x65, 0x49, 0x64, 0x12, 0x1b, 0x0a,
	0x09, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x72,
	0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x49, 0x64, 0x22, 0xb1, 0x03, 0x0a, 0x0b,
	0x45, 0x64, 0x67, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x3f, 0x0a, 0x0c, 0x63,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x1c, 0x2e, 0x72, 0x65, 0x70, 0x2e, 0x65, 0x64, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x45, 0x64, 0x67, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x3f, 0x0a, 0x0c,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x72, 0x65, 0x70, 0x2e, 0x65, 0x64, 0x67, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x45, 0x64, 0x67, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x12, 0x2b, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x13, 0x2e, 0x72, 0x65, 0x70, 0x2e, 0x65, 0x64, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x10,
	0x0a, 0x03, 0x72, 0x69, 0x64, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x72, 0x69, 0x64,
	0x12, 0x61, 0x0a, 0x1a, 0x6b, 0x61, 0x72, 0x70, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x5f, 0x61, 0x64,
	0x64, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x15,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x72, 0x65, 0x70, 0x2e, 0x65, 0x64, 0x67, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x4b, 0x61, 0x72, 0x70, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x41, 0x64, 0x64, 0x4e,
	0x6f, 0x64, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x17, 0x6b, 0x61, 0x72, 0x70,
	0x65, 0x6e, 0x74, 0x65, 0x72, 0x41, 0x64, 0x64, 0x4e, 0x6f, 0x64, 0x65, 0x43, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x12, 0x6a, 0x0a, 0x1d, 0x6b, 0x61, 0x72, 0x70, 0x65, 0x6e, 0x74, 0x65, 0x72,
	0x5f, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x63, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x18, 0x16, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x72, 0x65, 0x70,
	0x2e, 0x65, 0x64, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4b, 0x61, 0x72, 0x70, 0x65, 0x6e, 0x74,
	0x65, 0x72, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x43, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x52, 0x1a, 0x6b, 0x61, 0x72, 0x70, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65,
	0x6d, 0x6f, 0x76, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x22,
	0x3b, 0x0a, 0x16, 0x41, 0x64, 0x64, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x72, 0x6f,
	0x76, 0x69, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x0b, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x49, 0x64, 0x73, 0x22, 0x35, 0x0a, 0x19,
	0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x2a, 0x5b, 0x0a, 0x0f, 0x45, 0x64, 0x67, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x19, 0x0a, 0x15, 0x45, 0x64, 0x67, 0x65, 0x43, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x54, 0x79, 0x70, 0x65, 0x49, 0x67, 0x6e, 0x6f, 0x72, 0x65, 0x10,
	0x00, 0x12, 0x14, 0x0a, 0x10, 0x4b, 0x61, 0x72, 0x70, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x41, 0x64,
	0x64, 0x4e, 0x6f, 0x64, 0x65, 0x10, 0x11, 0x12, 0x17, 0x0a, 0x13, 0x4b, 0x61, 0x72, 0x70, 0x65,
	0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x10, 0x12,
	0x2a, 0xa8, 0x01, 0x0a, 0x0f, 0x45, 0x64, 0x67, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x19, 0x0a, 0x15, 0x45, 0x64, 0x67, 0x65, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x49, 0x67, 0x6e, 0x6f, 0x72, 0x65, 0x10, 0x00, 0x12,
	0x1b, 0x0a, 0x17, 0x4b, 0x61, 0x72, 0x70, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x41, 0x64, 0x64, 0x4e,
	0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x10, 0x21, 0x12, 0x1c, 0x0a, 0x18,
	0x4b, 0x61, 0x72, 0x70, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x41, 0x64, 0x64, 0x4e, 0x6f, 0x64, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x10, 0x22, 0x12, 0x1e, 0x0a, 0x1a, 0x4b, 0x61,
	0x72, 0x70, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x4e, 0x6f, 0x64,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x10, 0x23, 0x12, 0x1f, 0x0a, 0x1b, 0x4b, 0x61,
	0x72, 0x70, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x4e, 0x6f, 0x64,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x10, 0x24, 0x2a, 0x3c, 0x0a, 0x06, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0c, 0x0a, 0x08, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65,
	0x64, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x10, 0x01,
	0x12, 0x0a, 0x0a, 0x06, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07,
	0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x10, 0x03, 0x32, 0x57, 0x0a, 0x12, 0x45, 0x64, 0x67,
	0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x41, 0x0a, 0x07, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x12, 0x18, 0x2e, 0x72, 0x65, 0x70,
	0x2e, 0x65, 0x64, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x64, 0x67, 0x65, 0x43, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x1a, 0x18, 0x2e, 0x72, 0x65, 0x70, 0x2e, 0x65, 0x64, 0x67, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x45, 0x64, 0x67, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x28, 0x01,
	0x30, 0x01, 0x42, 0x42, 0x5a, 0x40, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x52, 0x61, 0x66, 0x61, 0x79, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x73, 0x2f, 0x6b, 0x61,
	0x72, 0x70, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x2d, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72,
	0x2d, 0x72, 0x61, 0x66, 0x61, 0x79, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x62, 0x72, 0x6f, 0x6b, 0x65,
	0x72, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_brokerproto_broker_proto_rawDescOnce sync.Once
	file_pkg_brokerproto_broker_proto_rawDescData = file_pkg_brokerproto_broker_proto_rawDesc
)

func file_pkg_brokerproto_broker_proto_rawDescGZIP() []byte {
	file_pkg_brokerproto_broker_proto_rawDescOnce.Do(func() {
		file_pkg_brokerproto_broker_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_brokerproto_broker_proto_rawDescData)
	})
	return file_pkg_brokerproto_broker_proto_rawDescData
}

var file_pkg_brokerproto_broker_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_pkg_brokerproto_broker_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pkg_brokerproto_broker_proto_goTypes = []interface{}{
	(EdgeCommandType)(0),               // 0: rep.edge.v1.EdgeCommandType
	(EdgeMessageType)(0),               // 1: rep.edge.v1.EdgeMessageType
	(Status)(0),                        // 2: rep.edge.v1.Status
	(*KarpenterAddNodeCommand)(nil),    // 3: rep.edge.v1.KarpenterAddNodeCommand
	(*KarpenterRemoveNodeCommand)(nil), // 4: rep.edge.v1.KarpenterRemoveNodeCommand
	(*EdgeCommand)(nil),                // 5: rep.edge.v1.EdgeCommand
	(*AddNodeResponsePayload)(nil),     // 6: rep.edge.v1.AddNodeResponsePayload
	(*RemoveNodeResponsePayload)(nil),  // 7: rep.edge.v1.RemoveNodeResponsePayload
}
var file_pkg_brokerproto_broker_proto_depIdxs = []int32{
	0, // 0: rep.edge.v1.EdgeCommand.command_type:type_name -> rep.edge.v1.EdgeCommandType
	1, // 1: rep.edge.v1.EdgeCommand.message_type:type_name -> rep.edge.v1.EdgeMessageType
	2, // 2: rep.edge.v1.EdgeCommand.status:type_name -> rep.edge.v1.Status
	3, // 3: rep.edge.v1.EdgeCommand.karpenter_add_node_command:type_name -> rep.edge.v1.KarpenterAddNodeCommand
	4, // 4: rep.edge.v1.EdgeCommand.karpenter_remove_node_command:type_name -> rep.edge.v1.KarpenterRemoveNodeCommand
	5, // 5: rep.edge.v1.EdgeCommandService.Execute:input_type -> rep.edge.v1.EdgeCommand
	5, // 6: rep.edge.v1.EdgeCommandService.Execute:output_type -> rep.edge.v1.EdgeCommand
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_pkg_brokerproto_broker_proto_init() }
func file_pkg_brokerproto_broker_proto_init() {
	if File_pkg_brokerproto_broker_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_brokerproto_broker_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KarpenterAddNodeCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_brokerproto_broker_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KarpenterRemoveNodeCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_brokerproto_broker_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EdgeCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_brokerproto_broker_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddNodeResponsePayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_brokerproto_broker_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveNodeResponsePayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_brokerproto_broker_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_brokerproto_broker_proto_goTypes,
		DependencyIndexes: file_pkg_brokerproto_broker_proto_depIdxs,
		EnumInfos:         file_pkg_brokerproto_broker_proto_enumTypes,
		MessageInfos:      file_pkg_brokerproto_broker_proto_msgTypes,
	}.Build()
	File_pkg_brokerproto_broker_proto = out.File
	file_pkg_brokerproto_broker_proto_rawDesc = nil
	file_pkg_brokerproto_broker_proto_goTypes = nil
	file_pkg_brokerproto_broker_proto_depIdxs = nil
}
