apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.leaderElection.namespace | quote }}
  labels:
    {{- include "karpenter-provider-rafay.labels" . | nindent 4 }}
    app.kubernetes.io/component: leader-election
