apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "karpenter-provider-rafay.fullname" . }}
  labels:
    {{- include "karpenter-provider-rafay.labels" . | nindent 4 }}
rules:
  - apiGroups: ["karpenter.sh"]
    resources: ["nodeclaims", "nodeclaims/status", "nodepools", "nodepools/status"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["karpenter.rafay.io"]
    resources: ["rafaynodeclasses", "rafaynodeclasses/status"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["nodes", "nodes/status", "pods", "pods/eviction", "events", "persistentvolumes", "persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["namespaces", "configmaps", "secrets", "serviceaccounts"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["daemonsets", "deployments", "replicasets", "statefulsets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["policy"]
    resources: ["poddisruptionbudgets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources:
      - volumeattachments
      - csinodes
      - csidrivers
      - storageclasses
      - csistoragecapacities
    verbs: ["get", "list", "watch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "karpenter-provider-rafay.fullname" . }}
  labels:
    {{- include "karpenter-provider-rafay.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "karpenter-provider-rafay.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "karpenter-provider-rafay.fullname" . }}
    namespace: {{ .Values.namespace.workload | quote }}
