apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "karpenter-provider-rafay.fullname" . }}
  namespace: {{ .Values.namespace.workload | quote }}
  labels:
    {{- include "karpenter-provider-rafay.labels" . | nindent 4 }}
